### ISSUE TITLE
Minor bug with remuw and remw instructions

### ISSUE THREAD

**Issue by phi-go** [d0iasm/rvemu#12]
Hey, I'm currently comparing my own emulator against this one and I think there is a really small bug with the remuw and remw instructions. Specifically, on a division by zero the 32-bit dividend is sign extended and it does not simply return the rs1 register value. To quote the spec: "Both REMW and REMUW always sign-extend the 32-bit result to 64 bits, including on a divide by zero."
I also confirmed this based on the source of the spike emulator.

Thanks for making this project!

**Comment by d0iasm** [comment]
Thanks for filing this issue!

Oh, you're right. I also confirmed it in the code of the spike.
remw: https://github.com/riscv/riscv-isa-sim/blob/master/riscv/insns/remw.h#L3
remuw: https://github.com/riscv/riscv-isa-sim/blob/master/riscv/insns/remuw.h#L3

This issue was fixed by this commit. Thank you so much :)
https://github.com/d0iasm/rvemu/commit/8600d31d0c190d308b12db59c5cc41e83a2e658d
